// <auto-generated />
namespace Repositorios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class clienteSalida : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clienteSalida));
        
        string IMigrationMetadata.Id
        {
            get { return "202006221243504_clienteSalida"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
